[config]
schemaVersion = "0.0.1"

[package]
namespace = "tesinormed"
name = "FAndCDaveCo"
versionNumber = "3.0.1"
description = "Adds an insurance system and a loan system"
websiteUrl = "https://github.com/tesinormed/FAndCDaveCo"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
BMX-LobbyCompatibility = "1.3.0"
WhiteSpike-Interactive_Terminal_API = "1.2.0"
MaxWasUnavailable-LethalModDataLib = "1.2.2"
xilophor-LethalNetworkAPI = "3.3.2"

[build]
icon = "./Assets/icon.png"
readme = "./README.markdown"
outdir = "./build"

[[build.copy]]
source = "./FAndCDaveCo/bin/tesinormed.FAndCDaveCo.dll"
target = "./BepInEx/plugins/tesinormed.FAndCDaveCo.dll"

[[build.copy]]
source = "./LICENSE.text"
target = "./LICENSE.text"

[publish]
repository = "https://thunderstore.io"
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["bepinex", "mods", "clientside", "serverside", "misc"]
